// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjrlASWak_iZRbcutQCIJRikKiLj8z930',
    appId: '1:199750027476:web:7aec4abc02ace88fe11341',
    messagingSenderId: '199750027476',
    projectId: 'instagram-ui-a8615',
    authDomain: 'instagram-ui-a8615.firebaseapp.com',
    storageBucket: 'instagram-ui-a8615.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAppmtWv1U7jJhNvMMIpSqGU4xte5lTkIg',
    appId: '1:199750027476:android:57a48ffeaad71b3ae11341',
    messagingSenderId: '199750027476',
    projectId: 'instagram-ui-a8615',
    storageBucket: 'instagram-ui-a8615.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9wizRKFBUYKfqY0jStQlN8ApXkoUnHG0',
    appId: '1:199750027476:ios:9030943f555497f6e11341',
    messagingSenderId: '199750027476',
    projectId: 'instagram-ui-a8615',
    storageBucket: 'instagram-ui-a8615.appspot.com',
    iosBundleId: 'com.example.instagramClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9wizRKFBUYKfqY0jStQlN8ApXkoUnHG0',
    appId: '1:199750027476:ios:9030943f555497f6e11341',
    messagingSenderId: '199750027476',
    projectId: 'instagram-ui-a8615',
    storageBucket: 'instagram-ui-a8615.appspot.com',
    iosBundleId: 'com.example.instagramClone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDjrlASWak_iZRbcutQCIJRikKiLj8z930',
    appId: '1:199750027476:web:1ba72c7f5d01e011e11341',
    messagingSenderId: '199750027476',
    projectId: 'instagram-ui-a8615',
    authDomain: 'instagram-ui-a8615.firebaseapp.com',
    storageBucket: 'instagram-ui-a8615.appspot.com',
  );
}
